package com.saurab.atomicledger.wallet;

public enum AuditAction {
	WALLET_CREATED,
	DEPOSIT_SUCCEEDED,
	DEPOSIT_DUPLICATE_REPLAY,
	TRANSFER_SUCCEEDED,
	TRANSFER_INSUFFICIENT_BALANCE,
	TRANSFER_DUPLICATE_REPLAY,
	RECONCILIATION_RUN,
	RECONCILIATION_FAILED
}
